name: file_write_as_bytes_compat
description: |
  Workaround for File.writeAsBytes not working bug.
  see) https://github.com/dart-lang/sdk/issues/36087
version: 0.0.1
homepage: https://github.com/vivitainc/flutter_file_write_as_bytes_compat

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
